# Generated by Django 4.0.7 on 2022-08-11 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100,
                 unique=True, verbose_name='nome')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='companies', to='tenant.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ('name',),
            },
        ),
    ]
