# Generated by Django 4.0.7 on 2022-08-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_employee_cpf_alter_employee_occupation'),
        ('sale', '0002_alter_sale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='employees_sales', to='crm.employee', verbose_name='vendedor'),
        ),
    ]
